In [2]:
import torch
import matplotlib.pyplot as plt
import math

torch.manual_seed(42)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print(device)

cuda


In [4]:
tokens = ["The", "cat", "sat", "on", "mat"]
seq_len = len(tokens)
d_model = 8

In [6]:
x = torch.randn(seq_len, d_model, device=device)
print("Tokens:", tokens)
print("Embedding Shape:", x.shape)

Tokens: ['The', 'cat', 'sat', 'on', 'mat']
Embedding Shape: torch.Size([5, 8])


In [7]:
d_k = 8

W_q = torch.randn(d_model, d_k, device=device)
W_k = torch.randn(d_model, d_k, device=device)
W_v = torch.randn(d_model, d_k, device=device)

print("W_q:", W_q.shape)
print("W_k:", W_k.shape)
print("W_v:", W_v.shape)

W_q: torch.Size([8, 8])
W_k: torch.Size([8, 8])
W_v: torch.Size([8, 8])


In [9]:
Q = x @ W_q
K = x @ W_k
V = x @ W_v

print("Q:", Q.shape)
print("K:", K.shape)
print("V:", V.shape)

Q: torch.Size([5, 8])
K: torch.Size([5, 8])
V: torch.Size([5, 8])


In [10]:
print("Token:", tokens[1])
print("Embedding:", x[1])

print("\nQuery:")
print(Q[1])

print("\nKey:")
print(K[1])

print("\nValue:")
print(V[1])

Token: cat
Embedding: tensor([ 0.2829, -0.8926, -0.1626, -0.8062, -0.1168, -1.6124, -0.1541, -0.0646],
       device='cuda:0')

Query:
tensor([ 0.7994,  0.9272, -2.1831, -3.2106,  0.7547,  0.1011,  2.9335, -0.1672],
       device='cuda:0')

Key:
tensor([ 0.8786, -4.6922,  0.4425,  1.0162,  0.7583,  0.1961, -0.4511, -0.8448],
       device='cuda:0')

Value:
tensor([ 3.1182, -0.1841, -1.4726, -0.1852, -0.8292,  1.2201, -3.4702,  1.3940],
       device='cuda:0')
